# Compatible version
mod.mcdep=~26.1
modstitch.platform=fabric-loom

# Development Version
deps.mc=26.1
deps.fabric=0.18.4
deps.fapi=0.143.14+26.1
# https://parchmentmc.org/docs/getting-started
deps.parchment=2025.12.20

deps.yacl=3.9.3+26.1-fabric

pub.target.versions=26.1 26.1.1 26.1.2
pub.target.platforms=fabric quilt

