# Compatible version
mod.mcdep==1.21.11
modstitch.platform=fabric-loom-remap

# Development Version
deps.mc=1.21.11
deps.fabric=0.18.3
deps.fapi=0.140.0+1.21.11
# https://parchmentmc.org/docs/getting-started
deps.parchment=2025.12.20

deps.yacl=3.8.2+1.21.11-fabric

pub.target.versions=1.21.11
pub.target.platforms=fabric quilt

